http:
  host: 0.0.0.0
  port: 1003
tcp: 
  host: 0.0.0.0
  port: 10003
swagger:
  host: 0.0.0.0:1003
jwt:
  secretKey: enterpriseMicroservicesNodeJS
  signOptions:
    expiresIn: '1d'
mongouri: mongodb+srv://ADMIN:fs2912fs@cluster0-gl0yj.mongodb.net/manage?retryWrites=true&w=majority